### ISSUE TITLE
Noticed a small issue.

### ISSUE THREAD

**Issue by 117** [SenneDirkx/leetcode#1]
For some reason the project is using Python not Go? 😉

**Comment by SenneDirkx** [comment]
The goal of this repository has been achieved: getting in contact with the one and only 2019 (or 117?). Cause he ain't responding on Discord 👎

Oh yea, to stay on track: that must've been a compiling issue. You know sometimes it compiles into Python randomly, not sure why.

**Comment by 117** [comment]
Do you use Telegram thats what i've been using..

**Comment by SenneDirkx** [comment]
I'll send you the details, sir.
